// Generated by gencpp from file service_demo/snedtaskResponse.msg
// DO NOT EDIT!


#ifndef SERVICE_DEMO_MESSAGE_SNEDTASKRESPONSE_H
#define SERVICE_DEMO_MESSAGE_SNEDTASKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_demo
{
template <class ContainerAllocator>
struct snedtaskResponse_
{
  typedef snedtaskResponse_<ContainerAllocator> Type;

  snedtaskResponse_()
    {
    }
  snedtaskResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::service_demo::snedtaskResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_demo::snedtaskResponse_<ContainerAllocator> const> ConstPtr;

}; // struct snedtaskResponse_

typedef ::service_demo::snedtaskResponse_<std::allocator<void> > snedtaskResponse;

typedef boost::shared_ptr< ::service_demo::snedtaskResponse > snedtaskResponsePtr;
typedef boost::shared_ptr< ::service_demo::snedtaskResponse const> snedtaskResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_demo::snedtaskResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_demo::snedtaskResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace service_demo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::service_demo::snedtaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_demo::snedtaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_demo::snedtaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_demo::snedtaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_demo::snedtaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_demo::snedtaskResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_demo::snedtaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::service_demo::snedtaskResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::service_demo::snedtaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_demo/snedtaskResponse";
  }

  static const char* value(const ::service_demo::snedtaskResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_demo::snedtaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::service_demo::snedtaskResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_demo::snedtaskResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct snedtaskResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_demo::snedtaskResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::service_demo::snedtaskResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_DEMO_MESSAGE_SNEDTASKRESPONSE_H
